### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by totelx56** [miromiro11/chromeRequests#1]
Traceback (most recent call last):
  File "examples.py", line 4, in <module>
    chromeRequests.loadLibrary("./GoLangSource/library.so")
  File "/chromeRequests/chromeRequests/chromeRequests.py", line 17, in loadLibrary
    library = ctypes.cdll.LoadLibrary(pathToLibrary)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./GoLangSource/library.so: invalid ELF header

**Comment by ZacharyHampton** [comment]
rebuild the binary for the os you are using

**Comment by sonymag** [comment]
same there

**Comment by ninjadoc107** [comment]
> rebuild the binary for the os you are using

how can I do this?
